export function fetchCandidateList(jobId) {
    return {
      job_id: jobId,
      job_title: '상품기획',
      company_id: 1,
      company_name: '삼성물산 패션부문',
      employment_type: '정규직',
      hiring_status: '진행중',
      interview_period: '2025.10.23 – 2025.12.15',
      total_applicants: 7, // 전체 인터뷰 완료 인원 수 (mock)
      applicants: [
        {
          applicant_id: 1,
          applicant_name: '김지원',
          interview_id: 90001,
          interview_date: '2025-10-27',
          interview_status: 'completed',
          school: '서울대학교',
          major: '의류학과',
          gpa: 3.8,
          scores: {
            final_score: 76.4,
            job_overall: 77.4,
            common_overall: 66.4,
            confidence_overall: 0.86,
          },
          // top_strengths: ['시즌 트렌드 분석', '매출·재고 데이터 기반 상품 구성'],
          // top_weaknesses: ['생산 리드타임 및 원가 구조 이해 부족'],
          ai_one_line_summary:
            '패션 도메인 이해와 데이터 기반 기획 역량이 균형 잡힌 상품기획형 인재입니다.',
          is_highlighted: true,
          is_bookmarked: true,
        },
        {
          applicant_id: 2,
          applicant_name: '박서진',
          interview_id: 90002,
          interview_date: '2025-03-21',
          interview_status: 'completed',
          school: '가천대학교',
          major: '패션디자인학과',
          gpa: 3.2,
          scores: {
            final_score: 69.5,
            job_overall: 68.0,
            common_overall: 70.3,
            confidence_overall: 0.69,
          },
          top_strengths: ['카테고리별 매출 분석', '리테일 운영 관점의 인사이트'],
          top_weaknesses: ['데이터 리터러시 부족', '브랜드 포지셔닝 이해 부족'],
          ai_one_line_summary:
            '현장 감각과 팀워크는 좋지만 데이터 분석과 기획 논리가 약해 추가 학습이 필요한 지원자입니다.',
          is_highlighted: false,
          is_bookmarked: true,
        },
        {
          applicant_id: 3,
          applicant_name: '이서윤',
          interview_id: 90003,
          interview_date: '2025-03-15',
          interview_status: 'completed',
          school: '성균관대학교',
          major: '글로벌리더학',
          gpa: 3.7,
          scores: {
            final_score: 65,
            job_overall: 62,
            common_overall: 70,
            confidence_overall: 0.74,
          },
          top_strengths: ['브랜드 포지셔닝 이해', '컬렉션 컨셉 스토리텔링'],
          top_weaknesses: ['정량 분석과 KPI 수립 경험 부족'],
          ai_one_line_summary:
            '브랜드·컬렉션 스토리 구성에 강점을 보이지만 수치 기반 기획은 보완 여지가 있는 지원자입니다.',
          is_highlighted: false,
          is_bookmarked: false,
        },
        {
          applicant_id: 4,
          applicant_name: '정하늘',
          interview_id: 90004,
          interview_date: '2025-03-18',
          interview_status: 'completed',
          school: '한국외국어대학교',
          major: '중국어과',
          gpa: 3.6,
          scores: {
            final_score: 72,
            job_overall: 75.4,
            common_overall: 63,
            confidence_overall: 0.71,
          },
          top_strengths: ['글로벌 마켓 리서치', '중국 시장 트렌드 파악'],
          top_weaknesses: ['내부 커뮤니케이션에서의 의사결정 드라이브'],
          ai_one_line_summary:
            '글로벌, 특히 중국 패션 시장 트렌드 인사이트가 강점인 지원자로 해외 리테일 확장에 기여 가능성이 있습니다.',
          is_highlighted: false,
          is_bookmarked: false,
        },
        {
          applicant_id: 5,
          applicant_name: '최민수',
          interview_id: 90005,
          interview_date: '2025-03-22',
          interview_status: 'completed',
          school: '부산대학교',
          major: '경제학과',
          gpa: 3.0,
          scores: {
            final_score: 62.3,
            job_overall: 61.0,
            common_overall: 63.5,
            confidence_overall: 0.62,
          },
          top_strengths: ['수요 예측 기본 이해', '정리된 커뮤니케이션'],
          top_weaknesses: ['패션 산업 지식 부족', '주도적 실행 사례 부족'],
          ai_one_line_summary:
            '기초 정량 감각은 있으나 패션 도메인 경험과 실행 드라이브가 부족해 멘토링이 필요한 지원자입니다.',
          is_highlighted: false,
          is_bookmarked: false,
        },
        {
          applicant_id: 6,
          applicant_name: '윤하나',
          interview_id: 90006,
          interview_date: '2025-03-24',
          interview_status: 'completed',
          school: '경기대학교',
          major: '영문학과',
          gpa: 2.8,
          scores: {
            final_score: 58.4,
            job_overall: 57.0,
            common_overall: 59.2,
            confidence_overall: 0.58,
          },
          top_strengths: ['고객 응대 경험', '팀 플레이'],
          top_weaknesses: ['데이터 분석 역량 부족', '패션 트렌드 이해 부족'],
          ai_one_line_summary:
            '서비스 마인드는 있으나 직무 적합성과 정량 역량이 낮아 추가 교육이 필수적인 지원자입니다.',
          is_highlighted: false,
          is_bookmarked: false,
        },
        {
          applicant_id: 7,
          applicant_name: '오상민',
          interview_id: 90007,
          interview_date: '2025-03-25',
          interview_status: 'completed',
          school: '청주대학교',
          major: '무역학과',
          gpa: 3.1,
          scores: {
            final_score: 60.7,
            job_overall: 59.5,
            common_overall: 62.0,
            confidence_overall: 0.6,
          },
          top_strengths: ['원가 협상 기초 경험', '성실한 태도'],
          top_weaknesses: ['패션 도메인 이해 부족', '데이터 기반 기획 경험 부족'],
          ai_one_line_summary:
            '원가 감각은 있지만 패션 상품기획 역량과 정량 설득력이 부족한 초기 단계 지원자입니다.',
          is_highlighted: false,
          is_bookmarked: false,
        },
      ],
      total_count: 7, // 현재 응답에 포함된 전체 지원자 수
      page: 1,
      page_size: 20,
    };
  }